#!/usr/bin/env python3
"""将 pages/ 目录下所有 HTML 文件编译为 _pages.js，供 index.html 直接读取。"""
import os, json

BASE = os.path.dirname(os.path.abspath(__file__))
pages_dir = os.path.join(BASE, 'pages')
out_file = os.path.join(BASE, '_pages.js')

pages = {}
for fname in sorted(os.listdir(pages_dir)):
    if not fname.endswith('.html'):
        continue
    page_id = fname.replace('.html', '')
    with open(os.path.join(pages_dir, fname), 'r', encoding='utf-8') as f:
        pages[page_id] = f.read()

js = '// Auto-generated by build.py — DO NOT EDIT\n'
js += 'var PAGE_CONTENT = ' + json.dumps(pages, ensure_ascii=False, indent=2) + ';\n'

with open(out_file, 'w', encoding='utf-8') as f:
    f.write(js)

total = sum(len(v) for v in pages.values())
print(f'Built _pages.js: {len(pages)} pages, {total:,} bytes total')
